ecommerce/ecommerce/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('listings/', include('listings.urls')),
    path('reviews/', include('reviews.urls')),
    path('watchlist/', include('watchlist.urls')),
    path('report/', include('report.urls')),
    path('shopping/', include('shopping.urls')),
    path('questions/', include('questions.urls')),
]

if settings.DEBUG:
    urlpatterns += static('/listings/imgs', document_root=os.path.join(settings.BASE_DIR, 'listings/imgs'))

ecommerce/listings/urls.py
from django.urls import path
from .views import *

app_name = 'listings'

urlpatterns = [
    path('create_product/', create_product_view.as_view(), name='create_product'),
    path('list_products/', list_products_view.as_view(), name='list_products'),

    path('delete_product/<int:pk>/', delete_product_view.as_view(), name='delete_product'),
    path('detail_product/<int:pk>/', detail_product_view.as_view(), name='detail_product'),
    path('update_product/<int:pk>/', update_product_view.as_view(), name='update_product'),

]

ecommerce/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('list_products/', views.list_products, name='list_products'),
]

ecommerce/report/urls.py
from django.urls import path
from .views import *

app_name = 'report'

urlpatterns = [
    path('create_report/<int:pk>/', report_create_view.as_view(), name='create_report'),
    path('list_reports/', report_list_view.as_view(), name='list_reports'),
    #path('delete_report/<int:pk>/', report_delete_view.as_view(), name='delete_report'),
    path('create_strike/<int:seller_pk>/', strike_create_view.as_view(), name='create_strike'),
    path('mark_seen/<int:report_pk>/', mark_report_seen, name='mark_report_seen'),
]

ecommerce/reviews/urls.py
from django.urls import path
from .views import *

app_name = 'reviews'

urlpatterns = [
    path('create_review/<int:pk>/', create_review_view.as_view(), name='create_review'),
    path('update_review/<int:pk>/', update_review_view.as_view(), name='update_review'),
    path('delete_review/<int:pk>/', delete_review_view.as_view(), name='delete_review'),
    path('create_seller_review/<int:pk>/', create_seller_review_view.as_view(), name='create_seller_review'),
    path('update_seller_review/<int:pk>/', update_seller_review_view.as_view(), name='update_seller_review'),
    path('delete_seller_review/<int:pk>/', delete_seller_review_view.as_view(), name='delete_seller_review'),
    path('list_seller_review/<int:pk>/', list_seller_review_view.as_view(), name='list_seller_review'),
    path('list_user_review/', list_user_review_view.as_view(), name='list_user_review'),
    path('list_user_seller_review/', list_user_seller_review_view.as_view(), name='list_user_seller_review'),
]

ecommerce/shopping/urls.py
from django.urls import path
from .views import *

app_name = 'shopping'

urlpatterns = [
    path('list_cart/', list_cart.as_view(), name='list_cart'),
    path('update_item_quantity/<int:item_pk>/', update_cart_item_quantity, name='update_item_quantity'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('checkout/', checkout_view.as_view(), name='checkout'),
    path('order_success/', order_success, name='order_success'),
    path('order_list/', order_list_view.as_view(), name='order_list'),
    path('order_seller_list', order_seller_list_view.as_view(), name='order_seller_list'),
    path('update_order/<int:item_id>/', update_order, name='order_update'),

]

ecommerce/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.home_signup, name='home_signup'),
    path('usersignup/', views.User_Signup_View.as_view(), name='user_signup'),
    path('sellersignup/', views.Seller_Signup_View.as_view(), name='seller_signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/user/<pk>', views.detail_profile_user.as_view(), name='profile_user'),
    path('profile/seller/<pk>', views.detail_profile_seller.as_view(), name='profile_seller'),
    path('profile/admin/<pk>', views.detail_profile_admin.as_view(), name='profile_admin'),
    path('profile/user/update/<pk>', views.update_profile_user.as_view(), name='update_profile_user'),
    path('profile/seller/update/<pk>', views.update_profile_seller.as_view(), name='update_profile_seller'),
    path('profile/admin/update/<pk>', views.update_profile_admin.as_view(), name='update_profile_admin'),
]

ecommerce/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class User(AbstractUser):
    is_registered_user = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=False)

class Registered_User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)
    PIVA = models.CharField(max_length=15)

    def __str__(self):
        return self.user.username

    def delete(self, *args, **kwargs):
        # Delete all products of the seller
        for product in self.products.all():
            product.delete()
        super().delete(*args, **kwargs)

ecommerce/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import User, Registered_User, Seller


class User_Signup_Form(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
        label='Nome utente',
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'username@example.com'}),
        error_messages={'required': 'Questo campo è obbligatorio.'},
    )
    phone = forms.CharField(
        max_length=20,
        label='Cellulare',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1234567890'}),
        error_messages = {'required': 'Questo campo è obbligatorio.'},
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
        label='Password',
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
        label='Conferma Password',
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'phone']

    # This decoration ensure that the save method is atomic, meaning that if an error occurs during the save process,
    # all the transaction is rolled back.
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_registered_user = True
        user.save()
        registered_user = Registered_User.objects.create(user=user)
        registered_user.phone = self.cleaned_data.get('phone')
        registered_user.save()
        return user


class Seller_Signup_Form(UserCreationForm):
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'username@example.com'}),
        error_messages={'required': 'Questo campo è obbligatorio.'},
    )
    phone = forms.CharField(
        max_length=20,
        label='Cellulare',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1234567890'}),
        error_messages={'required': 'Questo campo è obbligatorio.'},
    )

    PIVA = forms.CharField(
        max_length=15,
        label='Partita IVA',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '12345678901'}),
        error_messages={'required': 'Questo campo è obbligatorio.'},
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
        label='Nome utente',
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
        label='Password',
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
        label='Conferma Password',
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'PIVA', 'password1', 'password2', 'phone']

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_seller = True
        user.save()
        seller = Seller.objects.create(user=user)
        seller.phone = self.cleaned_data.get('phone')
        seller.PIVA = self.cleaned_data.get('PIVA')
        seller.save()
        return user


# This form is used to update the information of a seller
class seller_update_form(forms.ModelForm):
    username = forms.CharField(
        max_length=150, required=True, label='Username',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )
    phone = forms.CharField(
        max_length=20, label='Cellulare',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    PIVA = forms.CharField(
        max_length=15, label='Partita IVA',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )


    class Meta:
        model = Seller
        fields = ['username', 'email', 'PIVA', 'phone']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].initial = self.instance.user.username  # Set the initial value of the field
        self.fields['email'].initial = self.instance.user.email  # Set the initial value of the field

    def save(self, commit=True):
        instance = super().save(commit=False)
        # Update the username of the connected user
        instance.user.username = self.cleaned_data['username']
        instance.user.email = self.cleaned_data['email']
        if commit:
            instance.user.save()
            instance.save()
        return instance


class user_update_form(forms.ModelForm):
    username = forms.CharField(
        max_length=150, required=True, label='Username',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )

    phone = forms.CharField(
        max_length=20, label='Cellulare',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Registered_User
        fields = ['username', 'email', 'phone']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].initial = self.instance.user.username  # Set the initial value of the field
        self.fields['email'].initial = self.instance.user.email  # Set the initial value of the field

    def save(self, commit=True):
        instance = super().save(commit=False)
        # Update the username of the connected user
        instance.user.username = self.cleaned_data['username']
        instance.user.email = self.cleaned_data['email']
        if commit:
            instance.user.save()
            instance.save()
        return instance

class admin_update_form(forms.ModelForm):
    username = forms.CharField(
        max_length=150, required=True, label='Username',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].initial = self.instance.username  # set the initial value of the field

    def save(self, commit=True):
        instance = super().save(commit=False)
        # Update the username of the connected user
        instance.username = self.cleaned_data['username']
        instance.user.email = self.cleaned_data['email']
        if commit:
            instance.save()
        return instance

ecommerce/users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from .forms import *
from listings.models import Category
from shopping.models import Cart
from .mixins import *

def home_signup(request):
    return render(request, 'users/home_signup.html')


class User_Signup_View(CreateView):
    model = User
    form_class = User_Signup_Form
    template_name = 'users/user_signup.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['user_type'] = 'utente'
        return ctx

    def form_valid(self , form):
        user = form.save()

        Cart.objects.create(user=user)

        return redirect('users:login')

    def dispatch(self, request, *args, **kwargs):
        # If the user is authenticated, redirect him to the home page
        if request.user.is_authenticated:
            return redirect('pages:home_page')
        return super().dispatch(request, *args, **kwargs)


class Seller_Signup_View(CreateView):
    model = User
    form_class = Seller_Signup_Form
    template_name = 'users/user_signup.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['user_type'] = 'venditore'
        return ctx

    def form_valid(self , form):
        user = form.save()

        Cart.objects.create(user=user)

        return redirect('users:login')

    def dispatch(self, request, *args, **kwargs):
        # If the user is authenticated, redirect him to the home page
        if request.user.is_authenticated:
            return redirect('pages:home_page')
        return super().dispatch(request, *args, **kwargs)



# Page to show information of a user/seller/admin
class detail_profile_user(reguser_required_mixin, DetailView):
    model = Registered_User
    template_name = 'users/profile_user.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['categories'] = Category.objects.all()
        return ctx

class detail_profile_seller(seller_required_mixin, DetailView):
    model = Seller
    template_name = 'users/profile_seller.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['categories'] = Category.objects.all()
        return ctx

class detail_profile_admin(admin_required_mixin, DetailView):
    model = User
    template_name = 'users/profile_admin.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['categories'] = Category.objects.all()
        return ctx


class update_profile_user(reguser_required_mixin, UpdateView):
    model = Registered_User
    form_class = user_update_form
    template_name = 'users/update_profile_user.html'

    def get_success_url(self):
        pk = self.get_context_data()['object'].pk
        return reverse('users:profile_user', kwargs={'pk': pk})

class update_profile_seller(seller_required_mixin, UpdateView):
    model = Seller
    form_class = seller_update_form
    #fields = '__all__'
    template_name = 'users/update_profile_seller.html'


    def get_success_url(self):
        pk = self.get_context_data()['object'].pk
        return reverse('users:profile_seller', kwargs={'pk': pk})

class update_profile_admin(admin_required_mixin, UpdateView):
    model = User
    form_class = admin_update_form
    template_name = 'users/update_profile_admin.html'

    def get_success_url(self):
        pk = self.get_context_data()['object'].pk
        return reverse('users:profile_admin', kwargs={'pk': pk})

ecommerce/users/templates/users/home_signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/sign.css' %}">
{% endblock %}


{% block title %} Home Signup {% endblock %}

{% block content %}
    <div class="login-wrapper">
        Hai già un account? <a href="{% url 'users:login' %}">Accedi</a>
    </div>


    <div class="container">
        <div class="d-flex justify-content-between align-items-center py-2">
            <!-- Logo Section -->
            <div class="logo">
                <a href="{% url 'pages:home_page' %}">
                    <img src="{% static 'imgs/logo.png' %}" alt="Logo" width="150" height="30">
                </a>
            </div>
        </div>

        <div class="title">Registra un nuovo account</div>
        <div class="subtitle">Seleziona il tipo di account che vuoi creare</div>

        <div class="btn-group">
            <a href="{% url 'users:user_signup' %}" class="btn buttons">Utente</a>
            <a href="{% url 'users:seller_signup' %}" class="btn buttons">Venditore</a>
        </div>
    </div>
    
    {% include 'footer.html' %}
{% endblock %}

ecommerce/users/templates/users/profile_admin.html
{% extends 'base_pages.html' %}

{% block title %} Admin profile {% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="bg-light p-3 my-3 text-center">
                    <h2>{{ object.username }}</h2>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Info personali</h5> <br>
                        <p class="card-text"><strong>Email:</strong> {{ object.email }}</p>
                        <p class="card-text"><strong>Iscritto in data:</strong> {{ object.date_joined }}</p>
                        <a href="{% url 'users:update_profile_admin' object.pk %}" class="btn btn-light">Modifica</a>
                    </div>
                </div>
                <div class="my-3 d-flex flex-column align-items-start">
                    <a href="{% url 'report:list_reports' %}" class="btn custom-button mb-2">Gestisci segnalazioni</a>
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/users/templates/users/profile_seller.html
{% extends 'base_pages.html' %}

{% block title %} Seller profile {% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="bg-light p-3 my-3 text-center">
                    <h2>{{ object.user.username }}</h2>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Info personali</h5> <br>
                        <p class="card-text"><strong>Email:</strong> {{ object.user.email }}</p>
                        <p class="card-text"><strong>Phone number:</strong> {{ object.phone }}</p>
                        <p class="card-text"><strong>P.IVA:</strong> {{ object.PIVA }}</p>
                        <p class="card-text"><strong>Iscritto in data:</strong> {{ object.user.date_joined }}</p>
                        <a href="{% url 'users:update_profile_seller' object.pk %}" class="btn btn-light">Modifica</a>
                    </div>
                </div>
                <div class="my-3 d-flex flex-row align-items-start">
                    <div class="d-flex flex-column">
                        <a href="{% url 'listings:list_products' %}" class="btn custom-button mb-2">Info sui prodotti</a>
                        <a href="{% url 'listings:create_product' %}" class="btn custom-button-reg mb-2">Aggiungi prodotto</a>
                    </div>
                    <div class="d-flex flex-column ml-2 mx-2">
                        <a href="{% url 'watchlist:list_favourites' %}" class="btn custom-button mb-2">Lista preferiti</a>
                        <a href="{% url 'reviews:list_seller_review' object.pk %}" class="btn custom-button-reg">Visualizza recensioni</a>
                    </div>
                    <div class="d-flex flex-column ml-2">
                        <a href="{% url 'shopping:order_list' %}" class="btn custom-button mb-2">I miei ordini</a>
                        <a href="{% url 'shopping:order_seller_list' %}" class="btn custom-button-reg">Ordini sui miei prodotti</a>
                    </div>
                </div>
                {% if object.strikes.count > 0 %}
                    <p class="text-muted">Attenzione: hai {{ object.strikes.count }} strikes</p>
                {% endif %}
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/users/templates/users/profile_user.html
{% extends 'base_pages.html' %}

{% block title %} User profile {% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="bg-light p-3 my-3 text-center">
                    <h2>{{ object.user.username }}</h2>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Info personali</h5> <br>
                        <p class="card-text"><strong>Email:</strong> {{ object.user.email }}</p>
                        <p class="card-text"><strong>Phone number:</strong> {{ object.phone }}</p>
                        <p class="card-text"><strong>Iscritto in data:</strong> {{ object.user.date_joined }}</p>
                        <a href="{% url 'users:update_profile_user' object.pk %}" class="btn btn-light">Modifica</a>
                    </div>
                </div>
                <div class="my-3 d-flex flex-row align-items-start">
                    <div class="d-flex flex-column">
                        <a href="{% url 'watchlist:list_favourites' %}" class="btn custom-button me-2 mb-2">Lista preferiti</a>
                        <a href="{% url 'reviews:list_user_review' %}" class="btn custom-button-reg">Visualizza recensioni sui prodotti</a>
                    </div>
                    <div class="d-flex flex-column ml-2 mx-2">
                        <a href="{% url 'shopping:order_list' %}" class="btn custom-button me-2 mb-2">I miei ordini</a>
                        <a href="{% url 'reviews:list_user_seller_review' %}" class="btn custom-button-reg me-2">Visualizza recensioni sui venditori</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/users/templates/users/update_profile_admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Update admin {% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Modifica profilo</h2>
                <div class="card mb-3">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-light">Modifica</button>
                            <a href="{% url 'users:profile_admin' object.pk %}" class="btn btn-secondary">Annulla</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/users/templates/users/update_profile_seller.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Update seller {% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Modifica profilo</h2>
                <div class="card mb-3">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-light">Modifica</button>
                            <a href="{% url 'users:profile_seller' object.pk %}" class="btn btn-secondary">Annulla</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/users/templates/users/update_profile_user.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Update user {% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Modifica profilo</h2>
                <div class="card mb-3">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-light">Modifica</button>
                            <a href="{% url 'users:profile_user' object.pk %}" class="btn btn-secondary">Annulla</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/users/templates/users/user_signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/sign.css' %}">
{% endblock %}

{% block title %} User Signup {% endblock %}

{% block content %}
    <div class="login-wrapper">
        Hai già un account? <a href="{% url 'users:login' %}">Accedi</a>
    </div>

    {% include 'head.html' %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h3 class="text-center">Registrati come {{ user_type }}</h3>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn buttons btn-block">Registrati</button>
                </form>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}


{% endblock %}