ecommerce/ecommerce/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('listings/', include('listings.urls')),
    path('reviews/', include('reviews.urls')),
    path('watchlist/', include('watchlist.urls')),
    path('report/', include('report.urls')),
    path('shopping/', include('shopping.urls')),
    path('questions/', include('questions.urls')),
]

if settings.DEBUG:
    urlpatterns += static('/listings/imgs', document_root=os.path.join(settings.BASE_DIR, 'listings/imgs'))

ecommerce/listings/urls.py
from django.urls import path
from .views import *

app_name = 'listings'

urlpatterns = [
    path('create_product/', create_product_view.as_view(), name='create_product'),
    path('list_products/', list_products_view.as_view(), name='list_products'),

    path('delete_product/<int:pk>/', delete_product_view.as_view(), name='delete_product'),
    path('detail_product/<int:pk>/', detail_product_view.as_view(), name='detail_product'),
    path('update_product/<int:pk>/', update_product_view.as_view(), name='update_product'),

]

ecommerce/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('list_products/', views.list_products, name='list_products'),
]

ecommerce/reviews/urls.py
from django.urls import path
from .views import *

app_name = 'reviews'

urlpatterns = [
    path('create_review/<int:pk>/', create_review_view.as_view(), name='create_review'),
    path('update_review/<int:pk>/', update_review_view.as_view(), name='update_review'),
    path('delete_review/<int:pk>/', delete_review_view.as_view(), name='delete_review'),
    path('create_seller_review/<int:pk>/', create_seller_review_view.as_view(), name='create_seller_review'),
    path('update_seller_review/<int:pk>/', update_seller_review_view.as_view(), name='update_seller_review'),
    path('delete_seller_review/<int:pk>/', delete_seller_review_view.as_view(), name='delete_seller_review'),
    path('list_seller_review/<int:pk>/', list_seller_review_view.as_view(), name='list_seller_review'),
    path('list_user_review/', list_user_review_view.as_view(), name='list_user_review'),
    path('list_user_seller_review/', list_user_seller_review_view.as_view(), name='list_user_seller_review'),
]

ecommerce/reviews/models.py
from django.db import models

class Review(models.Model):
    product = models.ForeignKey('listings.Product', on_delete=models.CASCADE, related_name='reviews')
    reg_user = models.ForeignKey('users.Registered_User', on_delete=models.CASCADE, related_name='product_reviews')
    title = models.CharField(max_length=100)
    rating = models.IntegerField() #Value between 1 and 5
    comment = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, editable=False, null=True)

    class Meta:
        unique_together = ['product', 'reg_user']

    def __str__(self):
        return f'{self.product.title} - {self.reg_user.user.username}'


class Seller_Review(models.Model):
    reg_user = models.ForeignKey('users.Registered_User', on_delete=models.CASCADE, related_name='seller_reviews_by_user')
    seller = models.ForeignKey('users.Seller', on_delete=models.CASCADE, related_name='seller_reviews')
    title = models.CharField(max_length=100)
    comment = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, editable=False, null=True)

    class Meta:
        unique_together = ['reg_user', 'seller']

    def __str__(self):
        return f'{self.reg_user.user.username} - {self.seller.user.username}'

ecommerce/reviews/forms.py
from django import forms
from .models import Review, Seller_Review


class review_create_form(forms.ModelForm):
    title = forms.CharField(
        max_length=100, required=True,
        label='Titolo',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Quali sono le cose più importanti da sapere?'}),
    )

    comment = forms.CharField(
        label='Aggiungi una recensione scritta',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Che cosa ti è piaciuto e che cosa no?'}),
    )

    rating = forms.IntegerField(
        required=True,
        label='Valutazione complessiva',
        widget=forms.HiddenInput(attrs={'class': 'form-control', 'id': 'rating'}),
    )

    class Meta:
        model = Review
        fields = ['rating', 'title', 'comment']

class seller_review_create_form(forms.ModelForm):
    title = forms.CharField(
        max_length=100, required=True,
        label='Titolo',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Quali sono le cose più importanti da sapere?'}),
    )

    comment = forms.CharField(
        label='Aggiungi una recensione scritta',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Che cosa ti è piaciuto e che cosa no?'}),
    )

    class Meta:
        model = Seller_Review
        fields = ['title', 'comment']

ecommerce/reviews/views.py
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from listings.models import Product, Category
from users.models import Seller
from users.mixins import reguser_general_mixin, review_owner_mixin
from .forms import *

class create_review_view(reguser_general_mixin, CreateView):
    model = Review
    template_name = 'reviews/create_review.html'
    form_class = review_create_form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # To get all the Categories for search bar
        context['categories'] = Category.objects.all()
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        product_id = self.kwargs.get('pk')
        form.instance.product = Product.objects.get(pk=product_id)
        form.instance.reg_user = self.request.user.registered_user
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('listings:detail_product', kwargs={'pk': self.kwargs['pk']})


class update_review_view(review_owner_mixin, UpdateView):
    model = Review
    template_name = 'reviews/update_review.html'
    form_class = review_create_form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        review = self.get_object()
        # To get all the Categories for search bar
        context['categories'] = Category.objects.all()
        context['product'] = review.product


        succ = self.request.GET.get('succ')
        if succ and succ == 'profile':
            context['succ'] = 'profile'
        else:
            context['succ'] = None

        return context

    def get_success_url(self):
        #If in the URL there is a query parameter 'succ' with value 'profile', redirect to the user's reviews list
        succ = self.request.GET.get('succ')
        if succ and succ=='profile':
            return reverse('reviews:list_user_review')
        review = self.get_object()
        return reverse('listings:detail_product', kwargs={'pk': review.product.pk})


class delete_review_view(review_owner_mixin, DeleteView):
    model = Review
    template_name = 'reviews/delete_review.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        succ = self.request.GET.get('succ')
        if succ and succ == 'profile':
            context['succ'] = 'profile'
        else:
            context['succ'] = None

        return context



    def get_success_url(self):
        # If in the URL there is a query parameter 'succ' with value 'profile', redirect to the user's reviews list
        succ = self.request.GET.get('succ')
        if succ and succ == 'profile':
            return reverse('reviews:list_user_review')
        review = self.get_object()
        return reverse('listings:detail_product', kwargs={'pk': review.product.pk})



class create_seller_review_view(reguser_general_mixin, CreateView):
    model = Seller_Review
    template_name = 'reviews/create_seller_review.html'
    form_class = seller_review_create_form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # To get all the Categories for search bar
        context['categories'] = Category.objects.all()
        context['seller'] = Seller.objects.get(pk=self.kwargs['pk'])

        product_pk = self.request.GET.get('product_pk')
        if product_pk:
            context['product'] = product_pk
        else:
            context['product'] = None

        return context

    def form_valid(self, form):
        seller_id = self.kwargs.get('pk')
        seller = Seller.objects.get(pk=seller_id)
        form.instance.seller = seller
        form.instance.reg_user = self.request.user.registered_user
        return super().form_valid(form)

    def get_success_url(self):
        product_pk = self.request.GET.get('product_pk')
        if product_pk:
            return reverse('listings:detail_product', kwargs={'pk': product_pk})
        else:
            return reverse('pages:home_page')


class update_seller_review_view(review_owner_mixin ,UpdateView):
    model = Seller_Review
    template_name = 'reviews/update_seller_review.html'
    form_class = seller_review_create_form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        seller_review = self.get_object()
        # To get all the Categories for search bar
        context['categories'] = Category.objects.all()
        context['seller'] = seller_review.seller

        succ = self.request.GET.get('succ')
        if succ and succ == 'profile':
            context['succ'] = 'profile'
        else:
            context['succ'] = None

        product_pk = self.request.GET.get('product_pk')
        if product_pk:
            context['product'] = product_pk
        else:
            context['product'] = None

        return context

    def get_success_url(self):
        # If in the URL there is a query parameter 'succ' with value 'profile', redirect to the user's reviews list
        succ = self.request.GET.get('succ')

        product_pk = self.request.GET.get('product_pk')
        if product_pk:
            return reverse('listings:detail_product', kwargs={'pk': product_pk})
        elif succ and succ == 'profile':
            return reverse('reviews:list_user_seller_review')
        else:
            return reverse('pages:home_page')


class delete_seller_review_view(review_owner_mixin ,DeleteView):
    model = Seller_Review
    template_name = 'reviews/delete_seller_review.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        product_pk = self.request.GET.get('product_pk')
        if product_pk:
            context['product'] = product_pk
        else:
            context['product'] = None

        succ = self.request.GET.get('succ')
        if succ and succ == 'profile':
            context['succ'] = 'profile'
        else:
            context['succ'] = None

        return context

    def get_success_url(self):
        # If in the URL there is a query parameter 'succ' with value 'profile', redirect to the user's reviews list
        succ = self.request.GET.get('succ')

        product_pk = self.request.GET.get('product_pk')
        if product_pk:
            return reverse('listings:detail_product', kwargs={'pk': product_pk})
        elif succ and succ == 'profile':
            return reverse('reviews:list_user_seller_review')
        else:
            return reverse('pages:home_page')


# List of reviews for a seller
class list_seller_review_view(ListView):
    model = Seller_Review
    template_name = 'reviews/list_seller_review.html'
    paginate_by = 5

    def get_queryset(self):
        seller_pk = self.kwargs.get('pk')
        return Seller_Review.objects.filter(seller=Seller.objects.get(pk=seller_pk)).order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # To get all the Categories for search bar
        context['categories'] = Category.objects.all()

        seller_pk = self.kwargs.get('pk')
        context['seller'] = Seller.objects.get(pk=seller_pk)

        context['seller_reviews'] = Seller_Review.objects.filter(seller=context['seller'])

        # Take the product_pk from the query parameters
        product_pk = self.request.GET.get('product_pk')
        if product_pk:
            context['product'] = product_pk
        else:
            context['product'] = None

        return context


# List of reviews for products made by a user
class list_user_review_view(reguser_general_mixin ,ListView):
    model = Review
    template_name = 'reviews/list_user_review.html'
    paginate_by = 5

    def get_queryset(self):
        return Review.objects.filter(reg_user=self.request.user.registered_user).order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # To get all the Categories for search bar
        context['categories'] = Category.objects.all()
        context['reg_user'] = self.request.user.registered_user

        return context



# List of reviews for sellers made by a user
class list_user_seller_review_view(reguser_general_mixin ,ListView):
    model = Seller_Review
    template_name = 'reviews/list_user_seller_review.html'
    paginate_by = 5

    def get_queryset(self):
        return Seller_Review.objects.filter(reg_user=self.request.user.registered_user).order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # To get all the Categories for search bar
        context['categories'] = Category.objects.all()
        context['reg_user'] = self.request.user.registered_user

        return context

ecommerce/reviews/templates/reviews/create_review.html
{% extends 'base_pages.html' %}
{% load static %}

{% block title %}Make review{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/star.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h3 class="mt-4">Crea una recensione</h3>
        <div class="col-md-5 row mb-3">
            <div class="col-md-2">
                <div class="image-container" style="border: 1px solid #ddd;">
                    <img src="{{ product.image1.url }}" alt="{{ product.name }}" class="card-img-top product-image">
                </div>
            </div>
            <div class="col-md-9">
                <p>{{ product.title }}</p>
            </div>
        </div>

        <hr class="mb-3">

        <form method="POST">
            {% csrf_token %}
            <label for="rating" class="rating-label">Valutazione complessiva</label>
            <div id="star-rating" class="mb-3 star-icons">
                <i class="far fa-star" data-value="1"></i>
                <i class="far fa-star" data-value="2"></i>
                <i class="far fa-star" data-value="3"></i>
                <i class="far fa-star" data-value="4"></i>
                <i class="far fa-star" data-value="5"></i>
            </div>

            {{ form.rating }}

            <div class="mb-3">
                <p class="rating-label">Aggiungi un titolo</p>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <p class="rating-label">Aggiungi una recensione scritta</p>
                {{ form.comment }}
            </div>
            <button type="submit" class="btn btn-success btn-block">Invia</button>
            <a class="btn btn-secondary" href="{% url 'listings:detail_product' product.pk %}">Annulla</a>
        </form>


    </div>

    {% include 'footer.html' %}

    <script src="{% static 'js/star.js' %}"></script>


{% endblock %}

ecommerce/reviews/templates/reviews/create_seller_review.html
{% extends 'base_pages.html' %}
{% load static %}

{% block title %}Make seller review{% endblock %}

{% block content %}
    <div class="container">
        <h3 class="mt-4">Crea una recensione per {{ seller.user.username }}</h3>

        <hr class="mb-3">

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success btn-block">Invia</button>
            {% if product %}
                <a class="btn btn-secondary" href="{% url 'listings:detail_product' product %}">Annulla</a>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'pages:home_page' %}">Annulla</a>
            {% endif %}

        </form>


    </div>

    {% include 'footer.html' %}


{% endblock %}

ecommerce/reviews/templates/reviews/delete_review.html
{% extends 'base.html' %}

{% block title %}Delete review{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-5">
        <h2>Riepilogo</h2>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ review.title }}</h5>
                <p class="card-text">{{ review.comment }}</p>

                <div class="rating">
                    {% for i in "12345" %}
                        {% if review.rating >= forloop.counter %}
                            <i class="fas fa-star star"></i> <!-- full star -->
                        {% else %}
                            <i class="far fa-star star"></i> <!-- empty star -->
                        {% endif %}
                    {% endfor %}
                </div>

            </div>
        </div>
        <div class="mt-3">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Si elimina</button>
                {% if succ == 'profile' %}
                    <a href="{% url 'reviews:list_user_review' %}" class="btn btn-secondary">Torna indietro</a>
                {% else %}
                    <a href="{% url 'listings:detail_product' review.product.pk %}" class="btn btn-secondary">Torna indietro</a>
                {% endif %}

            </form>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/reviews/templates/reviews/delete_seller_review.html
{% extends 'base.html' %}

{% block title %}Delete seller review{% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-5">
        <h2>Riepilogo</h2>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ seller_review.title }}</h5>
                <p class="card-text">{{ seller_review.comment }}</p>

            </div>
        </div>
        <div class="mt-3">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Si elimina</button>
                {% if product %}
                    <a class="btn btn-secondary" href="{% url 'listings:detail_product' product %}">Torna indietro</a>
                {% elif succ == 'profile' %}
                    <a class="btn btn-secondary" href="{% url 'reviews:list_user_seller_review' %}">Torna indietro</a>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'pages:home_page' %}">Torna indietro</a>
                {% endif %}
            </form>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/reviews/templates/reviews/list_seller_review.html
{% extends 'base_pages.html' %}

{% block title %} List seller review {% endblock %}

{% block content %}
    <div class="container">
        <div class="description w-100 d-flex justify-content-between align-items-center p-2">
            <h1 class="display-4">Recensioni di {{ seller.user.username }}</h1>
            {% if product %}
                <a href="{% url 'listings:detail_product' product %}" class="btn btn-outline-secondary">Torna indietro</a>
            {% endif %}
        </div>
        <hr>
        <div class="row">
            {% for review in object_list %}
                <div class="col-md-12 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">{{ review.reg_user.user.username }}</h4>
                            <h5 class="card-subtitle">{{ review.title }}</h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ review.comment }}</p>
                        </div>
                    </div>
                    <hr>
                </div>
            {% endfor %}
        </div>

    {% include 'nav_pages.html' %}
    </div>


    {% include 'footer.html' %}
{% endblock %}

ecommerce/reviews/templates/reviews/list_user_review.html
{% extends 'base_pages.html' %}

{% block title %} List user review {% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="description w-100 d-flex justify-content-between align-items-center p-2">
            <h1 class="display-4">Le tue recensioni sui prodotti</h1>
        </div>
        <hr>

        <div class="row">
            {% for review in object_list %}
                <div class="col-md-12 mb-4">
                    <div class="card">
                        <div class="card-header">

                            <div class="col-md-5 row mb-3">
                                <div class="col-md-2">
                                    <div class="image-container" style="border: 1px solid #ddd;">
                                        <a href="{% url 'listings:detail_product' review.product.pk %}" target="_blank">
                                            <img src="{{ review.product.image1.url }}" alt="{{ product.name }}" class="card-img-top product-image">
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <p>
                                        <a href="{% url 'listings:detail_product' review.product.pk %}" style="text-decoration: none; color: inherit;" target="_blank">{{ review.product.title }}</a>
                                    </p>
                                </div>
                            </div>

                        </div>

                        <div class="d-flex align-items-center">
                            <!-- Stars -->
                            <div class="d-flex align-items-center me-2 mx-2 my-2"> <!-- To see stars next -->
                                {% for i in "12345" %}
                                    {% if review.rating >= forloop.counter %}
                                        <i class="fas fa-star"></i> <!-- full star -->
                                    {% else %}
                                        <i class="far fa-star"></i> <!-- empty star -->
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <!-- Title of review -->
                            <p class="mb-0 fw-bold">{{ review.title }}</p>
                        </div>
                    <p class="my-3 mx-2">{{ review.comment }}</p>

                    </div>
                    <div class="my-2">
                        <a href="{% url 'reviews:update_review' review.pk %}?succ=profile" class="btn btn-outline-primary">Modifica</a>
                        <a href="{% url 'reviews:delete_review' review.pk %}?succ=profile" class="btn btn-outline-danger">Elimina</a>
                    </div>

                    <hr>
                </div>
            {% endfor %}
        </div>

    {% include 'nav_pages.html' %}

    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/reviews/templates/reviews/list_user_seller_review.html
{% extends 'base_pages.html' %}

{% block title %} List user review {% endblock %}

{% block content %}
    <div class="container">
        <div class="description w-100 d-flex justify-content-between align-items-center p-2">
            <h1 class="display-4">Le tue recensioni sui venditori</h1>
        </div>
        <hr>

        <div class="row">
            {% for review in object_list %}
                <div class="col-md-12 mb-4">
                    <div class="card">
                        <div class="card-header">

                            <h3>{{ review.seller.user.username }}</h3>

                            <!-- Title of review -->
                            <p class="mb-0 fw-bold">{{ review.title }}</p>
                        </div>
                    <p class="my-3 mx-2">{{ review.comment }}</p>

                    </div>
                    <div class="my-2">
                        <a href="{% url 'reviews:update_seller_review' review.pk %}?succ=profile" class="btn btn-outline-primary">Modifica</a>
                        <a href="{% url 'reviews:delete_seller_review' review.pk %}?succ=profile" class="btn btn-outline-danger">Elimina</a>
                    </div>

                    <hr>
                </div>
            {% endfor %}
        </div>

    {% include 'nav_pages.html' %}

    </div>

    {% include 'footer.html' %}
{% endblock %}

ecommerce/reviews/templates/reviews/update_review.html
{% extends 'base_pages.html' %}
{% load static %}

{% block title %}Update review{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/star.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h3 class="mt-4">Modifica recensione</h3>
        <div class="col-md-5 row mb-3">
            <div class="col-md-2">
                <div class="image-container" style="border: 1px solid #ddd;">
                    <img src="{{ product.image1.url }}" alt="{{ product.name }}" class="card-img-top product-image">
                </div>
            </div>
            <div class="col-md-9">
                <p>{{ product.title }}</p>
            </div>
        </div>

        <hr class="mb-3">

        <form method="POST">
            {% csrf_token %}
            <label for="rating" class="rating-label">Valutazione complessiva</label>
            <div id="star-rating" class="mb-3 star-icons">
                <i class="far fa-star" data-value="1"></i>
                <i class="far fa-star" data-value="2"></i>
                <i class="far fa-star" data-value="3"></i>
                <i class="far fa-star" data-value="4"></i>
                <i class="far fa-star" data-value="5"></i>
            </div>

            {{ form.rating }}

            <div class="mb-3">
                <p class="rating-label">Modifica titolo</p>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <p class="rating-label">Modifica recensione scritta</p>
                {{ form.comment }}
            </div>
            <button type="submit" class="btn btn-success btn-block">Invia</button>
            {% if succ == 'profile' %}
                <a class="btn btn-secondary" href="{% url 'reviews:list_user_review' %}">Annulla</a>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'listings:detail_product' product.pk %}">Annulla</a>
            {% endif %}
        </form>


    </div>

    {% include 'footer.html' %}

    <script src="{% static 'js/star.js' %}"></script>
{% endblock %}

ecommerce/reviews/templates/reviews/update_seller_review.html
{% extends 'base_pages.html' %}
{% load static %}

{% block title %}Update seller review{% endblock %}

{% block content %}
    <div class="container">
        <h3 class="mt-4">Modifica recensione</h3>
        <hr class="mb-3">

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success btn-block">Invia</button>
            {% if product  %}
                <a class="btn btn-secondary" href="{% url 'listings:detail_product' product %}">Annulla</a>
            {% elif succ == 'profile' %}
                <a class="btn btn-secondary" href="{% url 'reviews:list_user_seller_review' %}">Annulla</a>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'pages:home_page' %}">Annulla</a>
            {% endif %}
        </form>


    </div>

    {% include 'footer.html' %}

    <script src="{% static 'js/star.js' %}"></script>
{% endblock %}