ecommerce/ecommerce/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('listings/', include('listings.urls')),
    path('reviews/', include('reviews.urls')),
    path('watchlist/', include('watchlist.urls')),
    path('report/', include('report.urls')),
    path('shopping/', include('shopping.urls')),
    path('questions/', include('questions.urls')),
]

if settings.DEBUG:
    urlpatterns += static('/listings/imgs', document_root=os.path.join(settings.BASE_DIR, 'listings/imgs'))

ecommerce/listings/urls.py
from django.urls import path
from .views import *

app_name = 'listings'

urlpatterns = [
    path('create_product/', create_product_view.as_view(), name='create_product'),
    path('list_products/', list_products_view.as_view(), name='list_products'),

    path('delete_product/<int:pk>/', delete_product_view.as_view(), name='delete_product'),
    path('detail_product/<int:pk>/', detail_product_view.as_view(), name='detail_product'),
    path('update_product/<int:pk>/', update_product_view.as_view(), name='update_product'),

]

ecommerce/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('list_products/', views.list_products, name='list_products'),
]

ecommerce/questions/urls.py
from django.urls import path
from .views import *

app_name = 'questions'

urlpatterns = [
    path('create_question/<int:pk>', create_question_view.as_view(), name='create_question'),
    path('questions/<int:question_id>/add_answer/', add_answer, name='add_answer'),
    path('list_questions/<int:pk>/', question_list_view.as_view(), name='list_questions'),
    path('approve_answer/<int:answer_pk>/', approve_answer, name='approve_answer'),

]

ecommerce/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.home_signup, name='home_signup'),
    path('usersignup/', views.User_Signup_View.as_view(), name='user_signup'),
    path('sellersignup/', views.Seller_Signup_View.as_view(), name='seller_signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/user/<pk>', views.detail_profile_user.as_view(), name='profile_user'),
    path('profile/seller/<pk>', views.detail_profile_seller.as_view(), name='profile_seller'),
    path('profile/admin/<pk>', views.detail_profile_admin.as_view(), name='profile_admin'),
    path('profile/user/update/<pk>', views.update_profile_user.as_view(), name='update_profile_user'),
    path('profile/seller/update/<pk>', views.update_profile_seller.as_view(), name='update_profile_seller'),
    path('profile/admin/update/<pk>', views.update_profile_admin.as_view(), name='update_profile_admin'),
]

ecommerce/listings/models.py
import shutil

from django.db import models
import os
from users.models import Seller
from reviews.models import Review

# Define path to save images of products
def product_image_path(instance, filename):
    # Ensure that the instance has a pk
    if not instance.pk:
        instance.save()  # Save the instance to obtain a pk

    # Generate the path to save the image
    return os.path.join(f'listings/imgs/{instance.pk}', filename)

class Product(models.Model):

    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, related_name='products')
    title = models.CharField(max_length=255)

    description = models.TextField()

    #Images of product, the seller must upload at least one image
    image1 = models.ImageField(upload_to=product_image_path, blank=False, null=False)
    image2 = models.ImageField(upload_to=product_image_path, blank=True, null=True)
    image3 = models.ImageField(upload_to=product_image_path, blank=True, null=True)
    image4 = models.ImageField(upload_to=product_image_path, blank=True, null=True)
    image5 = models.ImageField(upload_to=product_image_path, blank=True, null=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    categories = models.ManyToManyField('Category', related_name='products')

    date = models.DateTimeField(auto_now_add=True, editable=False, null=True)

    sold = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        # Before save istance without pk
        if not self.pk:
            saved_images = [self.image1, self.image2, self.image3, self.image4, self.image5]
            self.image1 = None
            self.image2 = None
            self.image3 = None
            self.image4 = None
            self.image5 = None
            # To avoid saving two times pk, force_insert is set to None
            kwargs.pop('force_insert', None)
            super().save(*args, **kwargs)

            #Then save images
            self.image1, self.image2, self.image3, self.image4, self.image5 = saved_images
            super().save(*args, **kwargs)
        else:
            super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        # Obtain the path of the folder containing the images of the product
        product_folder = os.path.join('listings/imgs', str(self.pk))

        # Verify that the folder exists and if there is, delete it
        if os.path.exists(product_folder) and os.path.isdir(product_folder):
            shutil.rmtree(product_folder)  # Remove the folder and its content

        # Delete the product from the database
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.title

    def decrease_quantity(self, n):
        if self.quantity - n < 0:
            self.quantity = 0
        else:
            self.quantity -= n
        self.save()

    def increase_quantity(self, n):
        self.quantity += n
        self.save()

    def increase_sold(self, n):
        self.sold += n
        self.save()

    def decrease_sold(self, n):
        if self.sold - n < 0:
            self.sold = 0
        else:
            self.sold -= n
        self.save()

    def average_rating(self):
        reviews = self.reviews.all()
        if reviews.exists():
            return sum(review.rating for review in reviews) / reviews.count()
        return 0 # If no reviews, return 0 because 0 reviews



class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'

ecommerce/listings/forms.py
from django import forms
from .models import Product, Category

class product_create_form(forms.ModelForm):
    title = forms.CharField(
        label='Titolo',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Titolo'}),
    )

    description = forms.CharField(
        label='Descrizione',
        widget=forms.Textarea(attrs={'class': 'form-control'}),
    )

    price = forms.DecimalField(
        label='Prezzo',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '99.99'}),
    )

    quantity = forms.IntegerField(
        label='Quantità',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1'}),
    )

    image1 = forms.ImageField(
        label='Immagine 1',
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
    )

    image2 = forms.ImageField(
        label='Immagine 2',
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
    )

    image3 = forms.ImageField(
        label='Immagine 3',
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
    )

    image4 = forms.ImageField(
        label='Immagine 4',
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
    )

    image5 = forms.ImageField(
        label='Immagine 5',
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
    )

    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label='Categorie'
    )


    class Meta:
        model = Product
        fields = ['title', 'description', 'image1', 'image2', 'image3', 'image4', 'image5', 'price', 'quantity', 'categories']

ecommerce/listings/views.py
from secrets import token_urlsafe

from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, ListView, DeleteView, DetailView, UpdateView

from watchlist.models import Favourite
from .models import *
from .forms import product_create_form
from users.mixins import seller_general_mixin, product_owner_mixin

class create_product_view(seller_general_mixin, CreateView):
    model = Product
    template_name = 'listings/create_product.html'
    form_class = product_create_form

    def get_success_url(self):
        return reverse('users:profile_seller', kwargs={'pk': self.object.seller.pk})

    def form_valid(self, form):
        # Save the product and set the seller
        form.instance.seller = self.request.user.seller
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seller'] = self.request.user.seller
        return context


class list_products_view(seller_general_mixin, ListView):
    model = Product
    template_name = 'listings/list_products.html'
    ordering = ['-date']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['seller'] = self.request.user.seller
        ctx['products'] = self.request.user.seller.products
        ctx['categories'] = Category.objects.all()
        return ctx


class delete_product_view(product_owner_mixin, DeleteView):
    model = Product
    template_name = 'listings/delete_product.html'

    def get_success_url(self):
        return reverse('listings:list_products')

class detail_product_view(DetailView):
    model = Product
    template_name = 'listings/detail_product.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.object
        context['categories'] = Category.objects.all()

        # This get the products of the same category of the current product
        related_products = Product.objects.filter(categories__in=self.object.categories.all()).exclude(id=self.object.id).distinct()[:5]
        context['related_products'] = related_products

        if self.request.user.is_authenticated and self.request.user.is_registered_user:
            # This is to take the review of the user if it exists
            user_review = self.object.reviews.filter(reg_user=self.request.user.registered_user).first()
            if user_review:
                context['user_review'] = user_review.pk
            else:
                context['user_review'] = None

            # This is used to check if the user has already reviewed the seller
            seller_review = self.object.seller.seller_reviews.filter(reg_user=self.request.user.registered_user).first()
            if seller_review:
                context['seller_review'] = seller_review.pk
            else:
                context['seller_review'] = None

            # This is used to check if the user has already reported the seller
            report = self.request.user.registered_user.reports.filter(seller=self.object.seller).first()
            if report:
                context['report'] = report.pk
            else:
                context['report'] = None

        else:
            context['user_review'] = None
            context['seller_review'] = None

        if self.request.user.is_authenticated:
            is_favorite = Favourite.objects.filter(user=self.request.user, product=self.object).exists()
            context['is_favorite'] = is_favorite
        else:
            context['is_favorite'] = False

        # Generate a token for buy the product
        if 'checkout_token' not in self.request.session:
            self.request.session['checkout_token'] = token_urlsafe(16)
        context['checkout_token'] = self.request.session['checkout_token']


        # Obtain questions and if the user has answered to them
        questions = self.object.questions.all()

        answered_map = {}
        for q in questions:
            # The map is used to check if the user has answered to the question. If the user is not authenticated,
            # we suppose that he has not answered
            if self.request.user.is_authenticated:
                answered_map[q.pk] = q.answer.filter(user=self.request.user).exists()
            else:
                answered_map[q.pk] = False

        context['answered_map'] = answered_map

        return context

class update_product_view(product_owner_mixin, UpdateView):
    #BUG: even if there are images for a product, the form for the images shows 'No file chosen'. If you press 'Modifica'
    # the images there are.
    model = Product
    template_name = 'listings/update_product.html'
    form_class = product_create_form


    def get_success_url(self):
        return reverse('listings:list_products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seller'] = self.request.user.seller
        return context

ecommerce/listings/templates/listings/create_product.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}

{% block title %} Adding product {% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="card mx-auto border-0" style="width: 50rem;">
        <div class="card-body">
            <h3 class="card-title">Aggiungi un nuovo prodotto</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success btn-block">Inserisci</button>
                <a class="btn btn-secondary" href="{% url 'users:profile_seller' seller.pk %}">Annulla</a>
            </form>
        </div>
    </div>


    {% include 'footer.html' %}
{% endblock %}

ecommerce/listings/templates/listings/delete_product.html
{% extends 'base.html' %}

{% block title %} Delete product {% endblock %}

{% block content %}
    {% include 'head.html' %}
    <div class="container mt-5">
        <h2>Riepilogo</h2>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <p class="card-text"><strong>Prezzo:</strong> {{ product.price }}</p>
                <p class="card-text"><strong>Quantità:</strong> {{ product.quantity }}</p>
                <p class="card-text"><strong>Categorie:</strong>
                    {% for category in product.categories.all %}
                        <span class="badge bg-secondary">{{ category }}</span>
                    {% endfor %}
                <div class="product-images">
                    {% if product.image1 %}
                        <img src="{{ product.image1.url }}" alt="Product Image 1" class="img-thumbnail" style="width: 100px; height: 100px;">
                    {% endif %}
                    {% if product.image2 %}
                        <img src="{{ product.image2.url }}" alt="Product Image 2" class="img-thumbnail" style="width: 100px; height: 100px;">
                    {% endif %}
                    {% if product.image3 %}
                        <img src="{{ product.image3.url }}" alt="Product Image 3" class="img-thumbnail" style="width: 100px; height: 100px;">
                    {% endif %}
                    {% if product.image4 %}
                        <img src="{{ product.image4.url }}" alt="Product Image 4" class="img-thumbnail" style="width: 100px; height: 100px;">
                    {% endif %}
                    {% if product.image5 %}
                        <img src="{{ product.image5.url }}" alt="Product Image 5" class="img-thumbnail" style="width: 100px; height: 100px;">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="mt-3">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Si elimina</button>
                <a href="{% url 'listings:list_products' %}" class="btn btn-secondary">Torna indietro</a>
            </form>
        </div>
    </div>

    {% include 'footer.html' %}

{% endblock %}

ecommerce/listings/templates/listings/list_products.html
{% extends 'base_pages.html' %}
{% load static %}

{% block title %} List products {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="display-4">Prodotti</h1>
                <label for="searchInput" class="form-label">Cerca tra i tuoi prodotti</label>
                <input type="text" id="searchInput" class="form-control mb-4" placeholder="Cerca per titolo...">
                <div class="row" id="productList">
                    {% for product in products.all %}
                        <div class="col-md-4 mb-4 product-card">
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="card-title">{{ product.title }}</h5>
                                </div>
                                <div id="carousel{{ forloop.counter }}" class="carousel slide" data-bs-ride="carousel">
                                    <div class="carousel-inner">
                                        <div class="carousel-item active">
                                            <img src="{{ product.image1.url }}" class="d-block w-100 img-size" alt="immagine 1">
                                        </div>
                                        {% if product.image2 %}
                                            <div class="carousel-item">
                                                <img src="{{ product.image2.url }}" class="d-block w-100 img-size" alt="immagine 2">
                                            </div>
                                        {% endif %}
                                        {% if product.image3 %}
                                            <div class="carousel-item">
                                                <img src="{{ product.image3.url }}" class="d-block w-100 img-size" alt="immagine 3">
                                            </div>
                                        {% endif %}
                                        {% if product.image4 %}
                                            <div class="carousel-item">
                                                <img src="{{ product.image4.url }}" class="d-block w-100 img-size" alt="immagine 4">
                                            </div>
                                        {% endif %}
                                        {% if product.image5 %}
                                            <div class="carousel-item">
                                                <img src="{{ product.image5.url }}" class="d-block w-100 img-size" alt="immagine 5">
                                            </div>
                                        {% endif %}
                                    </div>
                                    <button class="carousel-control-prev" type="button" data-bs-target="#carousel{{ forloop.counter }}" data-bs-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Previous</span>
                                    </button>
                                    <button class="carousel-control-next" type="button" data-bs-target="#carousel{{ forloop.counter }}" data-bs-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Next</span>
                                    </button>
                                </div>
                                <div class="card-body">
                                    <p class="card-text">Categorie:</p>
                                    {% for category in product.categories.all %}
                                        <span class="badge bg-secondary">{{ category }}</span>
                                    {% endfor %}
                                    <p class="card-text">Prezzo: EUR {{ product.price }}</p>
                                    <div class="d-flex">
                                        <p class="card-text">Quantity: {{ product.quantity }}</p>
                                        <p class="text-muted ms-auto">Venduti: {{ product.sold }}</p>
                                    </div>

                                    <a href="{% url 'listings:update_product' product.pk %}" class="btn btn-primary">Modifica</a>
                                    <a href="{% url 'listings:delete_product' product.pk %}" class="btn btn-danger">Elimina</a>
                                    <a href="{% url 'listings:detail_product' product.pk %}" class="btn btn-success">Vedi sullo store</a>
                                    <a href="{% url 'questions:list_questions' product.pk %}" class="btn btn-dark">Q&A</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}

    <script src="{% static 'js/list_products.js' %}"></script>
{% endblock %}

ecommerce/listings/templates/listings/update_product.html
{% extends 'base.html' %}

{% block title %} Update product {% endblock %}

{% block content %}
    {% include 'head.html' %}

    <div class="card mx-auto border-0" style="width: 50rem;">
        <div class="card-body">
            <h3 class="card-title">Modifica prodotto</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success btn-block">Modifica</button>
                <a class="btn btn-secondary" href="{% url 'users:profile_seller' seller.pk %}">Annulla</a>
            </form>
        </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}