ecommerce/ecommerce/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls')),
    path('listings/', include('listings.urls')),
    path('reviews/', include('reviews.urls')),
    path('watchlist/', include('watchlist.urls')),
    path('report/', include('report.urls')),
    path('shopping/', include('shopping.urls')),
    path('questions/', include('questions.urls')),
]

if settings.DEBUG:
    urlpatterns += static('/listings/imgs', document_root=os.path.join(settings.BASE_DIR, 'listings/imgs'))

ecommerce/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('list_products/', views.list_products, name='list_products'),
]

ecommerce/shopping/urls.py
from django.urls import path
from .views import *

app_name = 'shopping'

urlpatterns = [
    path('list_cart/', list_cart.as_view(), name='list_cart'),
    path('update_item_quantity/<int:item_pk>/', update_cart_item_quantity, name='update_item_quantity'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('checkout/', checkout_view.as_view(), name='checkout'),
    path('order_success/', order_success, name='order_success'),
    path('order_list/', order_list_view.as_view(), name='order_list'),
    path('order_seller_list', order_seller_list_view.as_view(), name='order_seller_list'),
    path('update_order/<int:item_id>/', update_order, name='order_update'),

]

ecommerce/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.home_signup, name='home_signup'),
    path('usersignup/', views.User_Signup_View.as_view(), name='user_signup'),
    path('sellersignup/', views.Seller_Signup_View.as_view(), name='seller_signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/user/<pk>', views.detail_profile_user.as_view(), name='profile_user'),
    path('profile/seller/<pk>', views.detail_profile_seller.as_view(), name='profile_seller'),
    path('profile/admin/<pk>', views.detail_profile_admin.as_view(), name='profile_admin'),
    path('profile/user/update/<pk>', views.update_profile_user.as_view(), name='update_profile_user'),
    path('profile/seller/update/<pk>', views.update_profile_seller.as_view(), name='update_profile_seller'),
    path('profile/admin/update/<pk>', views.update_profile_admin.as_view(), name='update_profile_admin'),
]

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block head %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    {% block content %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"></script>
</body>

</html>

ecommerce/templates/base_pages.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block head %} {% endblock %}
    <!-- First: to load bootstrap font. Third: to load symbols like symbol of cart -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    {% block navbar %}
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <!-- Logo -->
                <a class="navbar-brand" href="{% url 'pages:home_page' %}">
                    <img src="{% static 'imgs/logo.png' %}" alt="Logo" width="150" height="30" class="d-inline-block align-top">
                </a>

                <!-- Central search bar -->
                <div class="mx-auto" style="width: 60%;">
                    <form method="GET" action="{% url 'pages:list_products' %}" class="d-flex">
                        <!-- Dropdown menu for categories -->
                        <div class="form-group me-2">
                            <select name="category" class="form-select" id="categorySelect">
                                <option value="">Categorie</option>
                                {% for c in categories %}
                                    <option value="{{ c.name }}">{{ c.name }}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <!-- Search bar -->
                        <input class="form-control me-2" type="search" name="q" placeholder="Cerca prodotti..." aria-label="Search">

                        <!-- Dropdown menu for filtering -->
                        <div class="dropdown me-2">
                            <button class="btn custom-button-reg dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                Mostra
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="dropdown-item" onclick="setFilter('Mostra')">Mostra</a></li>
                                <li><a class="dropdown-item" onclick="setFilter('Prezzo basso-alto')">Prezzo: basso-alto</a></li>
                                <li><a class="dropdown-item" onclick="setFilter('Prezzo alto-basso')">Prezzo: alto-basso</a></li>
                                <li><a class="dropdown-item" onclick="setFilter('Più venduti')">Più venduti</a></li>
                            </ul>
                        </div>

                        <!-- Search button -->
                        <button class="btn custom-button" type="submit">Cerca</button>
                    </form>
                </div>

                <!-- Buttons Accedi and Registrati on the right -->
                {% if user.is_authenticated %}
                    <div class="d-flex">
                        {% if user.is_seller %}
                            <a class="btn custom-button me-2" href="{% url 'users:profile_seller' user.seller.pk%}">Profilo</a>
                        {% elif user.is_registered_user %}
                            <a class="btn custom-button me-2" href="{% url 'users:profile_user' user.registered_user.pk%}">Profilo</a>
                        {% else %}
                            <a class="btn custom-button me-2" href="{% url 'users:profile_admin' user.pk%}">Profilo</a>
                        {% endif %}
                        <form action="{% url 'users:logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn custom-button-reg">Logout</button>
                        </form>

                        <a href="{% url 'shopping:list_cart' %}" class="btn custom-button-reg me-2 mx-2">
                            <i class="fa fa-shopping-cart"></i>
                            {% if user.cart.total_items != 0 %}
                                <span id="small-quantity">{{ user.cart.total_items }}</span>
                            {% endif %}
                        </a>

                    </div>
                {% else %}
                    <div class="d-flex">
                        <a class="btn custom-button me-2" href="{% url 'users:login' %}">Accedi</a>
                        <a class="btn custom-button-reg" href="{% url 'users:home_signup' %}">Registrati</a>
                    </div>
                {% endif %}

            </div>
        </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}
    <script src="{% static 'js/search.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"></script>

</body>

</html>

ecommerce/templates/footer.html
<footer class="mt-5 mt-auto w-100">
    <div class="container-footer bg-light w-100 d-flex justify-content-between align-items-center p-2">
        <span class="ms-5">©Aresta Simone</span>
        <a href="/admin" class="text-muted">Admin</a>
    </div>
</footer>

<style>
    html, body {
        height: 100%;
    }

    body {
        display: flex;
        flex-direction: column;
    }

    .container-footer {
        flex: 1;
        width: 100%;
        margin-top: 20px;
    }
</style>



ecommerce/templates/head.html
{% load static %}

<div class="d-flex justify-content-center py-2 bg-light">
    <!-- Logo Section -->
    <div class="logo">
        <a href="{% url 'pages:home_page' %}">
            <img src="{% static 'imgs/logo.png' %}" alt="Logo" width="150" height="30">
        </a>
    </div>
</div>

ecommerce/templates/nav_pages.html
{% load custom_filters %}

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1&{{ request.GET|exclude_page }}">Inizio</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ request.GET|exclude_page }}">Precedente</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">Inizio</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link">Precedente</a>
            </li>
        {% endif %}

        <li class="page-item active show-page">
            <span class="page-link">{{ page_obj.number }} di {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ request.GET|exclude_page }}">Successiva</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&{{ request.GET|exclude_page }}">Fine</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">Successiva</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link">Fine</a>
            </li>
        {% endif %}
    </ul>
</nav>



<style>
    .page-link{
        color: black;
    }
</style>